  language: ruby

  rvm:
    - 2.1.9
    - 2.2.5
    - 2.3.1
    - 2.4
  before_script:
    - cp spec/support/moneta.example.yml spec/support/moneta.yml
    - bundle update
  script:
    - CODECLIMATE_REPO_TOKEN=d10be753ffa1a760be2df97c61673629a3fa86270cdd898250b8366213b0799c bundle exec rspec
